# Import most functionality from top level snakefile
# Here we just define the parameters that change and generate the params files

config["LAYOUT"] = "single"
config["REF"] = "/storage/resources/dbase/human/hg19/hg19.fa"
config["ENCODE"] = "GM12878_CTCF_ENCFF124LLI_ENCFF256QBB"
config["ENCDIR"] = "/storage/mgymrek/chipmunk_round2/encode/"
config["REGION"] = "chr22:1-51304566"
config["PEAKFILE"] = ""
config["MODELFILE"] = ""
config["C"] = 7

include: "/storage/mgymrek/workspace/tulip/paper-analyses/workflows/Snakefile"

NUMREADS = [1000, 10000, 100000, 1000000]

rule all:
    input:
        "summary_stats_readnum.tab"

rule create_params_file:
    output:
        "params/numreads{numreads,\d+}.params"
    shell:
        "echo --scale-outliers -c {config[C]} --numcopies 1000 --numreads {wildcards.numreads} --readlen 36 > {output}"

rule summarize_all:
    input:
        expand("metrics/numreads{numreads}.final.tab", numreads=NUMREADS)
    output:
        "summary_stats_readnum.tab"
    run:
       shell("head -n 1 {input[0]} | awk '{{print \"numreads\\t\" $0}}' >> {output}")
       for nr in NUMREADS:
           shell("tail -n 1 metrics/numreads%s.final.tab | awk '{{print \"%s\\t\" $0}}' >> {output}"%(nr, nr))
