# Import most functionality from top level snakefile
# Here we just define the parameters that change and generate the params files
#
# Simulated Peak files to use for evaluation
#/storage/pandaman/project/ChIPs-experiments/data/TF-SP1-sim.bed
#/storage/pandaman/project/ChIPs-experiments/data/HM-H3K27ac-sim.bed

config["LAYOUT"] = "paired"
config["REF"] = "/storage/resources/dbase/human/hg19/hg19.fa"
config["ENCODE"] = ""
config["ENCDIR"] = ""
config["REGION"] = "chr10:1-135534747"
#config["PEAKFILE"] = "/storage/pandaman/project/ChIPs-experiments/data/TF-SP1-sim.bed"
config["PEAKFILE"] = "/storage/pandaman/project/ChIPs-experiments/data/HM-H3K27ac-sim.bed"
config["MODELFILE"] = "params/simplified_GM12878_H3K27ac.json"
#config["MODELFILE"] = "params/simplified_GM12878_CTCF.json"
config["C"] = 4

include: "/storage/mlamkin/projects/tulip/paper-analyses/workflows/Snakefile"

PCR = [0.50, 0.625, 0.75, 0.875, 1.0]

rule all:
    input:
        "summary_stats_pcr.tab"

rule create_params_file:
    output:
        "params/pcr.{pcr,[\d.]+}.params"
    shell:
        "echo --scale-outliers -c {config[C]} --numcopies 1000 --numreads 100000 --thread 4 --readlen 36 --pcr_rate {wildcards.pcr} > {output}"

rule summarize_all:
    input:
        expand("metrics/pcr.{pcr}.final.tab", pcr=PCR)
    output:
        "summary_stats_pcr.tab"
    run:
       shell("head -n 1 {input[0]} | awk '{{print \"pcr\\t\" $0}}' >> {output}")
       for pp in PCR:
           shell("tail -n 1 metrics/pcr.%s.final.tab | awk '{{print \"%s\\t\" $0}}' >> {output}"%(pp, pp))
