# Import most functionality from top level snakefile
# Here we just define the parameters that change and generate the params files

include: "/storage/mgymrek/workspace/chips/paper-analyses/workflows/Snakefile"

rule all:
    input:
        expand("metrics/readlen{readlen}.numcopies{numcopies}.numreads{numreads}.final_log", readlen=[101], numcopies=[100], numreads=[10000])

rule create_params_file:
    output:
        "params/readlen{readlen,\d+}.numcopies{numcopies,\d+}.numreads{numreads,\d+}.params"
    shell:
        "echo --scale-outliers -c {config[C]} --numcopies {wildcards.numcopies} --numreads {wildcards.numreads} --readlen {wildcards.readlen} > {output}"

# This is primarily just to simplify the "all" rule, which now
# only needs to look for the final_log file
rule summarize:
    input:
        "tdfs/{sample}.tdf",
        "tdfs/{sample}_wce.tdf",
        "metrics/{sample}.narrow.metrics",
        "metrics/{sample}.broad.metrics"
    output:
        "metrics/{sample}.final_log"
    shell:
        "echo See output in {input[0]} {input[1]} {input[2]} {input[3]} > {output}"
