# Import most functionality from top level snakefile
# Here we just define the parameters that change and generate the params files
#
# Simulated Peak files to use for evaluation
#/storage/pandaman/project/ChIPs-experiments/data/TF-SP1-sim.bed
#/storage/pandaman/project/ChIPs-experiments/data/HM-H3K27ac-sim.bed

config["LAYOUT"] = "paired"
config["REF"] = "/storage/resources/dbase/human/hg19/hg19.fa"
config["ENCODE"] = ""
config["ENCDIR"] = ""
config["REGION"] = "chr10:1-135534747"
config["PEAKFILE"] = "/storage/pandaman/project/ChIPs-experiments/data/TF-SP1-sim.bed"
#config["PEAKFILE"] = "/storage/pandaman/project/ChIPs-experiments/data/HM-H3K27ac-sim.bed"
#config["MODELFILE"] = "params/simplified_GM12878_H3K4me3.json"
config["MODELFILE"] = "params/simplified_GM12878_CTCF.json"
config["C"] = 4

include: "/storage/mlamkin/projects/tulip/paper-analyses/workflows/Snakefile"

READLEN = [36, 100, 150, 200]

rule all:
    input:
        "summary_stats_readlen.tab"

rule create_params_file:
    output:
        "params/readlen{readlen,\d+}.params"
    shell:
        "echo --scale-outliers -c {config[C]} --thread 4 --numcopies 1000 --numreads 100000 --readlen {wildcards.readlen} > {output}"

rule summarize_all:
    input:
        expand("metrics/readlen{readlen}.final.tab", readlen=READLEN)
    output:
        "summary_stats_readlen.tab"
    run:
       shell("head -n 1 {input[0]} | awk '{{print \"readlen\\t\" $0}}' >> {output}")
       for rl in READLEN:
           shell("tail -n 1 metrics/readlen%s.final.tab | awk '{{print \"%s\\t\" $0}}' >> {output}"%(rl, rl))
